version: '3.8'

services:
  global_control_plane:
    image: kong/kuma-cp:0.0.0-preview.v33e2ed84e
    ports:
      - "5682:5681"
    command:
      - run
    environment:
      - CP_STORE=memory
      - KUMA_ENVIRONMENT=universal
      - KUMA_MODE=global
      - KUMA_EXPERIMENTAL_KDS_DELTA_ENABLED=true
      - KUMA_MULTIZONE_GLOBAL_KDS_TLS_ENABLED=false
      - KUMA_GENERAL_WORK_DIR=/tmp
  zone_control_plane:
    image: kong/kuma-cp:0.0.0-preview.v33e2ed84e
    command:
      - run
    environment:
      - CP_STORE=memory
      - KUMA_ENVIRONMENT=universal
      - KUMA_MODE=zone
      - KUMA_MULTIZONE_ZONE_NAME=zone1
      - KUMA_EXPERIMENTAL_KDS_DELTA_ENABLED=true
#      - KUMA_MULTIZONE_ZONE_GLOBAL_ADDRESS=grpc://global_control_plane:5685 # directly
#      - KUMA_MULTIZONE_ZONE_GLOBAL_ADDRESS=grpc://envoy:15685 # through Envoy egress
      #      - KUMA_MULTIZONE_ZONE_GLOBAL_ADDRESS=grpc://envoy:15685 # through Envoy ingress
      - KUMA_MULTIZONE_ZONE_GLOBAL_ADDRESS=grpc://nginx:35685 # through the GW
      - KUMA_MULTIZONE_ZONE_KDS_TLS_SKIP_VERIFY=true
  nginx:
    image: nginx:1.25.3-bookworm
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
  envoy_egress:
    image: envoyproxy/envoy:v1.27.1
    ports:
      - "9901:9901"
    privileged: true
    volumes:
      - ./envoy_egress.yaml:/etc/envoy/envoy.yaml
  envoy_ingress:
    image: envoyproxy/envoy:v1.27.1
    ports:
      - "9902:9901"
    privileged: true
    volumes:
      - ./envoy_ingress.yaml:/etc/envoy/envoy.yaml
